#!/bin/awk -f

BEGIN {
    system("mkdir -p ebin")
    system("ls /usr/lib/erlang/ | cat | awk 'match($0, /erts/) {print($0)}' > erts_version")
    getline ERTS_VERSION < "erts_version"
    system("gcc -O2 -march=native -funroll-loops -fomit-frame-pointer -flto -fPIC -shared -o ebin/fr.so src/crypto/fr.c -I $ERL_ROOT/user/include/ -I /usr/lib/erlang/" ERTS_VERSION "/include/")
    system("gcc -O2 -march=native -funroll-loops -fomit-frame-pointer -flto -fPIC -shared -o ebin/ed25519.so src/crypto/ed25519.c -I $ERL_ROOT/user/include/ -I /usr/lib/erlang/" ERTS_VERSION "/include/")
    system("rm erts_version")
    system("./rebar3 get-deps")
    system("./rebar3 compile")
    system("mkdir -p data")
    system("erl -pa ebin _build/default/lib/*/ebin/ -eval \"application:ensure_all_started(verkle).\"")
}
